{{- if .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubelink-usb.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if .Values.serviceAccount.agent.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubelink-usb.agentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
