#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

module="$(go list -m)"
output="${repo_root}/docs/CODE_REFERENCE.md"
tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

{
	echo "# Code Reference and Diagrams"
	echo
	echo "_Generated by \`hack/generate-code-reference.sh\` from the current Go source tree._"
	echo
	echo "## Unified Commenting System"
	echo
	echo "Use this structure for exported types and functions:"
	echo
	echo '```go'
	echo '// <Name> <short intent sentence>.'
	echo '//'
	echo '// Intent: <why this exists>'
	echo '// Inputs: <important inputs>'
	echo '// Outputs: <important outputs>'
	echo '// Errors: <error contract or current stub behavior>'
	echo '```'
	echo
	echo "## Package Inventory"
	echo
	echo "| Package | Role |"
	echo "| --- | --- |"
	go list ./... | while read -r pkg; do
		role="application code"
		case "${pkg}" in
			"${module}") role="controller manager entrypoint" ;;
			"${module}/cmd/agent") role="node agent entrypoint" ;;
			"${module}/cmd/controller") role="controller placeholder entrypoint" ;;
			"${module}/api/"*) role="CRD API types and deep-copy behavior" ;;
			"${module}/internal/controller") role="reconcile loop and object lifecycle" ;;
			"${module}/internal/agent") role="node-local discovery and attach/export stubs" ;;
			"${module}/internal/security") role="policy and TLS defaults" ;;
			"${module}/internal/usbip") role="USB/IP protocol/data-plane stubs" ;;
			"${module}/internal/backup") role="backup/restore storage and snapshot logic" ;;
			"${module}/internal/utils") role="pure helper functions" ;;
			"${module}/pkg/api") role="API package marker docs" ;;
		esac
		echo "| \`${pkg}\` | ${role} |"
	done
	echo
	echo "## Module Dependency Diagram (Generated)"
	echo
	echo '```mermaid'
	echo 'flowchart LR'
	go list -f '{{.ImportPath}} {{join .Imports " "}}' ./... | awk -v module="${module}" '
		{
			src=$1
			srcID=src
			gsub(/[^A-Za-z0-9]/, "_", srcID)
			for (i=2; i<=NF; i++) {
				dst=$i
				if (index(dst, module"/") != 1) {
					continue
				}
				dstID=dst
				gsub(/[^A-Za-z0-9]/, "_", dstID)
				key=src "->" dst
				if (!seen[key]++) {
					printf "    %s[\"%s\"] --> %s[\"%s\"]\n", srcID, src, dstID, dst
				}
			}
		}
	'
	echo '```'
	echo
	echo "## Controller Reconcile Flow"
	echo
	echo '```mermaid'
	echo 'flowchart TD'
	echo '    A[Fetch USBDevice] --> B{NotFound?}'
	echo '    B -- yes --> C[Return without requeue]'
	echo '    B -- no --> D{DeletionTimestamp set?}'
	echo '    D -- yes --> E[Remove finalizer if present]'
	echo '    E --> F[Return]'
	echo '    D -- no --> G[Ensure cleanup finalizer]'
	echo '    G --> H{Status.Phase empty?}'
	echo '    H -- yes --> I[Set PendingApproval + LastSeen + Healthy]'
	echo '    H -- no --> J[Keep status]'
	echo '    I --> K[Log discovery event]'
	echo '    J --> K'
	echo '```'
	echo
	echo "## Agent Discovery Event Normalization"
	echo
	echo '```mermaid'
	echo 'flowchart LR'
	echo '    C[fsnotify.Create] --> A[add]'
	echo '    R[fsnotify.Remove] --> B[remove]'
	echo '    W[Write/Chmod/Other] --> D[change]'
	echo '```'
} > "${tmp_file}"

mv "${tmp_file}" "${output}"
echo "Generated ${output}"
