//go:build !ignore_autogenerated

// Code generated by hand for initial scaffold compatibility.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *USBConnection) DeepCopyInto(out *USBConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBConnection) DeepCopy() *USBConnection {
	if in == nil {
		return nil
	}
	out := new(USBConnection)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnection) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBConnectionDeviceRef) DeepCopyInto(out *USBConnectionDeviceRef) { *out = *in }
func (in *USBConnectionDeviceRef) DeepCopy() *USBConnectionDeviceRef {
	if in == nil {
		return nil
	}
	out := new(USBConnectionDeviceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionList) DeepCopyInto(out *USBConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBConnection, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBConnectionList) DeepCopy() *USBConnectionList {
	if in == nil {
		return nil
	}
	out := new(USBConnectionList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBConnectionPodSelector) DeepCopyInto(out *USBConnectionPodSelector) {
	*out = *in
	if in.MatchLabels != nil {
		out.MatchLabels = make(map[string]string, len(in.MatchLabels))
		for k, v := range in.MatchLabels {
			out.MatchLabels[k] = v
		}
	}
}

func (in *USBConnectionPodSelector) DeepCopy() *USBConnectionPodSelector {
	if in == nil {
		return nil
	}
	out := new(USBConnectionPodSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionSpec) DeepCopyInto(out *USBConnectionSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.PodSelector != nil {
		out.PodSelector = new(USBConnectionPodSelector)
		in.PodSelector.DeepCopyInto(out.PodSelector)
	}
}

func (in *USBConnectionSpec) DeepCopy() *USBConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(USBConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionStatus) DeepCopyInto(out *USBConnectionStatus) {
	*out = *in
	if in.TunnelInfo != nil {
		out.TunnelInfo = new(USBConnectionTunnelInfo)
		*out.TunnelInfo = *in.TunnelInfo
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *USBConnectionStatus) DeepCopy() *USBConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(USBConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionTunnelInfo) DeepCopyInto(out *USBConnectionTunnelInfo) { *out = *in }
func (in *USBConnectionTunnelInfo) DeepCopy() *USBConnectionTunnelInfo {
	if in == nil {
		return nil
	}
	out := new(USBConnectionTunnelInfo)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevice) DeepCopyInto(out *USBDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBDevice) DeepCopy() *USBDevice {
	if in == nil {
		return nil
	}
	out := new(USBDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevice) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApproval) DeepCopyInto(out *USBDeviceApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBDeviceApproval) DeepCopy() *USBDeviceApproval {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApproval)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApproval) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApprovalConfig) DeepCopyInto(out *USBDeviceApprovalConfig) { *out = *in }
func (in *USBDeviceApprovalConfig) DeepCopy() *USBDeviceApprovalConfig {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalDeviceRef) DeepCopyInto(out *USBDeviceApprovalDeviceRef) { *out = *in }
func (in *USBDeviceApprovalDeviceRef) DeepCopy() *USBDeviceApprovalDeviceRef {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalDeviceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalList) DeepCopyInto(out *USBDeviceApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDeviceApproval, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDeviceApprovalList) DeepCopy() *USBDeviceApprovalList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApprovalPolicyRef) DeepCopyInto(out *USBDeviceApprovalPolicyRef) { *out = *in }
func (in *USBDeviceApprovalPolicyRef) DeepCopy() *USBDeviceApprovalPolicyRef {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalPolicyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalSpec) DeepCopyInto(out *USBDeviceApprovalSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.PolicyRef != nil {
		out.PolicyRef = new(USBDeviceApprovalPolicyRef)
		*out.PolicyRef = *in.PolicyRef
	}
	if in.ApprovedAt != nil {
		out.ApprovedAt = in.ApprovedAt.DeepCopy()
	}
	if in.ExpiresAt != nil {
		out.ExpiresAt = in.ExpiresAt.DeepCopy()
	}
}

func (in *USBDeviceApprovalSpec) DeepCopy() *USBDeviceApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalStatus) DeepCopyInto(out *USBDeviceApprovalStatus) {
	*out = *in
	if in.ApprovedAt != nil {
		out.ApprovedAt = in.ApprovedAt.DeepCopy()
	}
	if in.ExpiresAt != nil {
		out.ExpiresAt = in.ExpiresAt.DeepCopy()
	}
}

func (in *USBDeviceApprovalStatus) DeepCopy() *USBDeviceApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceConnectionInfo) DeepCopyInto(out *USBDeviceConnectionInfo) { *out = *in }
func (in *USBDeviceConnectionInfo) DeepCopy() *USBDeviceConnectionInfo {
	if in == nil {
		return nil
	}
	out := new(USBDeviceConnectionInfo)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceLifecycle) DeepCopyInto(out *USBDeviceLifecycle) { *out = *in }
func (in *USBDeviceLifecycle) DeepCopy() *USBDeviceLifecycle {
	if in == nil {
		return nil
	}
	out := new(USBDeviceLifecycle)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceList) DeepCopyInto(out *USBDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDevice, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDeviceList) DeepCopy() *USBDeviceList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicy) DeepCopyInto(out *USBDevicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *USBDevicePolicy) DeepCopy() *USBDevicePolicy {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicyList) DeepCopyInto(out *USBDevicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDevicePolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDevicePolicyList) DeepCopy() *USBDevicePolicyList {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicySelector) DeepCopyInto(out *USBDevicePolicySelector) {
	*out = *in
	if in.NodeNames != nil {
		out.NodeNames = make([]string, len(in.NodeNames))
		copy(out.NodeNames, in.NodeNames)
	}
}

func (in *USBDevicePolicySelector) DeepCopy() *USBDevicePolicySelector {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicySelector)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicySpec) DeepCopyInto(out *USBDevicePolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Approval.DeepCopyInto(&out.Approval)
	in.Restrictions.DeepCopyInto(&out.Restrictions)
	out.Lifecycle = in.Lifecycle
}

func (in *USBDevicePolicySpec) DeepCopy() *USBDevicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicyStatus) DeepCopyInto(out *USBDevicePolicyStatus) { *out = *in }
func (in *USBDevicePolicyStatus) DeepCopy() *USBDevicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceRestrictions) DeepCopyInto(out *USBDeviceRestrictions) {
	*out = *in
	if in.AllowedNodes != nil {
		out.AllowedNodes = make([]string, len(in.AllowedNodes))
		copy(out.AllowedNodes, in.AllowedNodes)
	}
	if in.AllowedNamespaces != nil {
		out.AllowedNamespaces = make([]string, len(in.AllowedNamespaces))
		copy(out.AllowedNamespaces, in.AllowedNamespaces)
	}
	if in.AllowedDeviceClasses != nil {
		out.AllowedDeviceClasses = make([]string, len(in.AllowedDeviceClasses))
		copy(out.AllowedDeviceClasses, in.AllowedDeviceClasses)
	}
}

func (in *USBDeviceRestrictions) DeepCopy() *USBDeviceRestrictions {
	if in == nil {
		return nil
	}
	out := new(USBDeviceRestrictions)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceSpec) DeepCopyInto(out *USBDeviceSpec) { *out = *in }
func (in *USBDeviceSpec) DeepCopy() *USBDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceStatus) DeepCopyInto(out *USBDeviceStatus) {
	*out = *in
	if in.ConnectionInfo != nil {
		out.ConnectionInfo = new(USBDeviceConnectionInfo)
		*out.ConnectionInfo = *in.ConnectionInfo
	}
	if in.LastSeen != nil {
		out.LastSeen = in.LastSeen.DeepCopy()
	}
}

func (in *USBDeviceStatus) DeepCopy() *USBDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceStatus)
	in.DeepCopyInto(out)
	return out
}
