//go:build !ignore_autogenerated

// Code generated by hand for initial scaffold compatibility.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *USBConnection) DeepCopyInto(out *USBConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBConnection) DeepCopy() *USBConnection {
	if in == nil {
		return nil
	}
	out := new(USBConnection)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnection) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBConnectionDeviceRef) DeepCopyInto(out *USBConnectionDeviceRef) { *out = *in }
func (in *USBConnectionDeviceRef) DeepCopy() *USBConnectionDeviceRef {
	if in == nil {
		return nil
	}
	out := new(USBConnectionDeviceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionList) DeepCopyInto(out *USBConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBConnection, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBConnectionList) DeepCopy() *USBConnectionList {
	if in == nil {
		return nil
	}
	out := new(USBConnectionList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBConnectionPodSelector) DeepCopyInto(out *USBConnectionPodSelector) {
	*out = *in
	if in.MatchLabels != nil {
		out.MatchLabels = make(map[string]string, len(in.MatchLabels))
		for k, v := range in.MatchLabels {
			out.MatchLabels[k] = v
		}
	}
}

func (in *USBConnectionPodSelector) DeepCopy() *USBConnectionPodSelector {
	if in == nil {
		return nil
	}
	out := new(USBConnectionPodSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionSpec) DeepCopyInto(out *USBConnectionSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.PodSelector != nil {
		out.PodSelector = new(USBConnectionPodSelector)
		in.PodSelector.DeepCopyInto(out.PodSelector)
	}
}

func (in *USBConnectionSpec) DeepCopy() *USBConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(USBConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionStatus) DeepCopyInto(out *USBConnectionStatus) {
	*out = *in
	if in.TunnelInfo != nil {
		out.TunnelInfo = new(USBConnectionTunnelInfo)
		*out.TunnelInfo = *in.TunnelInfo
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *USBConnectionStatus) DeepCopy() *USBConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(USBConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBConnectionTunnelInfo) DeepCopyInto(out *USBConnectionTunnelInfo) { *out = *in }
func (in *USBConnectionTunnelInfo) DeepCopy() *USBConnectionTunnelInfo {
	if in == nil {
		return nil
	}
	out := new(USBConnectionTunnelInfo)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevice) DeepCopyInto(out *USBDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBDevice) DeepCopy() *USBDevice {
	if in == nil {
		return nil
	}
	out := new(USBDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevice) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApproval) DeepCopyInto(out *USBDeviceApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBDeviceApproval) DeepCopy() *USBDeviceApproval {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApproval)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApproval) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApprovalConfig) DeepCopyInto(out *USBDeviceApprovalConfig) { *out = *in }
func (in *USBDeviceApprovalConfig) DeepCopy() *USBDeviceApprovalConfig {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalDeviceRef) DeepCopyInto(out *USBDeviceApprovalDeviceRef) { *out = *in }
func (in *USBDeviceApprovalDeviceRef) DeepCopy() *USBDeviceApprovalDeviceRef {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalDeviceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalList) DeepCopyInto(out *USBDeviceApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDeviceApproval, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDeviceApprovalList) DeepCopy() *USBDeviceApprovalList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceApprovalPolicyRef) DeepCopyInto(out *USBDeviceApprovalPolicyRef) { *out = *in }
func (in *USBDeviceApprovalPolicyRef) DeepCopy() *USBDeviceApprovalPolicyRef {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalPolicyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalSpec) DeepCopyInto(out *USBDeviceApprovalSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.PolicyRef != nil {
		out.PolicyRef = new(USBDeviceApprovalPolicyRef)
		*out.PolicyRef = *in.PolicyRef
	}
	if in.ApprovedAt != nil {
		out.ApprovedAt = in.ApprovedAt.DeepCopy()
	}
	if in.ExpiresAt != nil {
		out.ExpiresAt = in.ExpiresAt.DeepCopy()
	}
}

func (in *USBDeviceApprovalSpec) DeepCopy() *USBDeviceApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceApprovalStatus) DeepCopyInto(out *USBDeviceApprovalStatus) {
	*out = *in
	if in.ApprovedAt != nil {
		out.ApprovedAt = in.ApprovedAt.DeepCopy()
	}
	if in.ExpiresAt != nil {
		out.ExpiresAt = in.ExpiresAt.DeepCopy()
	}
}

func (in *USBDeviceApprovalStatus) DeepCopy() *USBDeviceApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceConnectionInfo) DeepCopyInto(out *USBDeviceConnectionInfo) { *out = *in }
func (in *USBDeviceConnectionInfo) DeepCopy() *USBDeviceConnectionInfo {
	if in == nil {
		return nil
	}
	out := new(USBDeviceConnectionInfo)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceLifecycle) DeepCopyInto(out *USBDeviceLifecycle) { *out = *in }
func (in *USBDeviceLifecycle) DeepCopy() *USBDeviceLifecycle {
	if in == nil {
		return nil
	}
	out := new(USBDeviceLifecycle)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceList) DeepCopyInto(out *USBDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDevice, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDeviceList) DeepCopy() *USBDeviceList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicy) DeepCopyInto(out *USBDevicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *USBDevicePolicy) DeepCopy() *USBDevicePolicy {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicyList) DeepCopyInto(out *USBDevicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDevicePolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDevicePolicyList) DeepCopy() *USBDevicePolicyList {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDevicePolicySelector) DeepCopyInto(out *USBDevicePolicySelector) {
	*out = *in
	if in.NodeNames != nil {
		out.NodeNames = make([]string, len(in.NodeNames))
		copy(out.NodeNames, in.NodeNames)
	}
}

func (in *USBDevicePolicySelector) DeepCopy() *USBDevicePolicySelector {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicySelector)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicySpec) DeepCopyInto(out *USBDevicePolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Approval.DeepCopyInto(&out.Approval)
	in.Restrictions.DeepCopyInto(&out.Restrictions)
	out.Lifecycle = in.Lifecycle
}

func (in *USBDevicePolicySpec) DeepCopy() *USBDevicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDevicePolicyStatus) DeepCopyInto(out *USBDevicePolicyStatus) { *out = *in }
func (in *USBDevicePolicyStatus) DeepCopy() *USBDevicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(USBDevicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceRestrictions) DeepCopyInto(out *USBDeviceRestrictions) {
	*out = *in
	if in.AllowedNodes != nil {
		out.AllowedNodes = make([]string, len(in.AllowedNodes))
		copy(out.AllowedNodes, in.AllowedNodes)
	}
	if in.AllowedNamespaces != nil {
		out.AllowedNamespaces = make([]string, len(in.AllowedNamespaces))
		copy(out.AllowedNamespaces, in.AllowedNamespaces)
	}
	if in.AllowedDeviceClasses != nil {
		out.AllowedDeviceClasses = make([]string, len(in.AllowedDeviceClasses))
		copy(out.AllowedDeviceClasses, in.AllowedDeviceClasses)
	}
}

func (in *USBDeviceRestrictions) DeepCopy() *USBDeviceRestrictions {
	if in == nil {
		return nil
	}
	out := new(USBDeviceRestrictions)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceSpec) DeepCopyInto(out *USBDeviceSpec) { *out = *in }
func (in *USBDeviceSpec) DeepCopy() *USBDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceStatus) DeepCopyInto(out *USBDeviceStatus) {
	*out = *in
	if in.ConnectionInfo != nil {
		out.ConnectionInfo = new(USBDeviceConnectionInfo)
		*out.ConnectionInfo = *in.ConnectionInfo
	}
	if in.LastSeen != nil {
		out.LastSeen = in.LastSeen.DeepCopy()
	}
}

func (in *USBDeviceStatus) DeepCopy() *USBDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// --- USBDeviceWhitelist DeepCopy ---

func (in *WhitelistEntry) DeepCopyInto(out *WhitelistEntry) {
	*out = *in
	if in.AddedAt != nil {
		out.AddedAt = in.AddedAt.DeepCopy()
	}
}

func (in *WhitelistEntry) DeepCopy() *WhitelistEntry {
	if in == nil {
		return nil
	}
	out := new(WhitelistEntry)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceWhitelist) DeepCopyInto(out *USBDeviceWhitelist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBDeviceWhitelist) DeepCopy() *USBDeviceWhitelist {
	if in == nil {
		return nil
	}
	out := new(USBDeviceWhitelist)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceWhitelist) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBDeviceWhitelistSpec) DeepCopyInto(out *USBDeviceWhitelistSpec) {
	*out = *in
	if in.Entries != nil {
		out.Entries = make([]WhitelistEntry, len(in.Entries))
		for i := range in.Entries {
			in.Entries[i].DeepCopyInto(&out.Entries[i])
		}
	}
}

func (in *USBDeviceWhitelistSpec) DeepCopy() *USBDeviceWhitelistSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceWhitelistSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceWhitelistStatus) DeepCopyInto(out *USBDeviceWhitelistStatus) {
	*out = *in
	if in.LastUpdated != nil {
		out.LastUpdated = in.LastUpdated.DeepCopy()
	}
}

func (in *USBDeviceWhitelistStatus) DeepCopy() *USBDeviceWhitelistStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceWhitelistStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceWhitelistList) DeepCopyInto(out *USBDeviceWhitelistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBDeviceWhitelist, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBDeviceWhitelistList) DeepCopy() *USBDeviceWhitelistList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceWhitelistList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBDeviceWhitelistList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- USBBackupConfig DeepCopy ---

func (in *BackupDestinationPVC) DeepCopyInto(out *BackupDestinationPVC) { *out = *in }

func (in *BackupDestinationPVC) DeepCopy() *BackupDestinationPVC {
	if in == nil {
		return nil
	}
	out := new(BackupDestinationPVC)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDestinationS3) DeepCopyInto(out *BackupDestinationS3) {
	*out = *in
	if in.SecretRef != nil {
		out.SecretRef = new(BackupDestinationSecret)
		*out.SecretRef = *in.SecretRef
	}
}

func (in *BackupDestinationS3) DeepCopy() *BackupDestinationS3 {
	if in == nil {
		return nil
	}
	out := new(BackupDestinationS3)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDestinationSecret) DeepCopyInto(out *BackupDestinationSecret) { *out = *in }

func (in *BackupDestinationSecret) DeepCopy() *BackupDestinationSecret {
	if in == nil {
		return nil
	}
	out := new(BackupDestinationSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDestinationConfigMap) DeepCopyInto(out *BackupDestinationConfigMap) { *out = *in }

func (in *BackupDestinationConfigMap) DeepCopy() *BackupDestinationConfigMap {
	if in == nil {
		return nil
	}
	out := new(BackupDestinationConfigMap)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDestination) DeepCopyInto(out *BackupDestination) {
	*out = *in
	if in.PVC != nil {
		out.PVC = new(BackupDestinationPVC)
		*out.PVC = *in.PVC
	}
	if in.S3 != nil {
		out.S3 = new(BackupDestinationS3)
		in.S3.DeepCopyInto(out.S3)
	}
	if in.ConfigMap != nil {
		out.ConfigMap = new(BackupDestinationConfigMap)
		*out.ConfigMap = *in.ConfigMap
	}
}

func (in *BackupDestination) DeepCopy() *BackupDestination {
	if in == nil {
		return nil
	}
	out := new(BackupDestination)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoRestoreConfig) DeepCopyInto(out *AutoRestoreConfig) { *out = *in }

func (in *AutoRestoreConfig) DeepCopy() *AutoRestoreConfig {
	if in == nil {
		return nil
	}
	out := new(AutoRestoreConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupConfigSpec) DeepCopyInto(out *USBBackupConfigSpec) {
	*out = *in
	in.Destination.DeepCopyInto(&out.Destination)
	out.AutoRestore = in.AutoRestore
}

func (in *USBBackupConfigSpec) DeepCopy() *USBBackupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(USBBackupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupConfigStatus) DeepCopyInto(out *USBBackupConfigStatus) {
	*out = *in
	if in.LastBackupTime != nil {
		out.LastBackupTime = in.LastBackupTime.DeepCopy()
	}
}

func (in *USBBackupConfigStatus) DeepCopy() *USBBackupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(USBBackupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupConfig) DeepCopyInto(out *USBBackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBBackupConfig) DeepCopy() *USBBackupConfig {
	if in == nil {
		return nil
	}
	out := new(USBBackupConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupConfig) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBBackupConfigList) DeepCopyInto(out *USBBackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBBackupConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBBackupConfigList) DeepCopy() *USBBackupConfigList {
	if in == nil {
		return nil
	}
	out := new(USBBackupConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupConfigList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- USBBackup DeepCopy ---

func (in *BackupItemCounts) DeepCopyInto(out *BackupItemCounts) { *out = *in }

func (in *BackupItemCounts) DeepCopy() *BackupItemCounts {
	if in == nil {
		return nil
	}
	out := new(BackupItemCounts)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupSpec) DeepCopyInto(out *USBBackupSpec) { *out = *in }

func (in *USBBackupSpec) DeepCopy() *USBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(USBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupStatus) DeepCopyInto(out *USBBackupStatus) {
	*out = *in
	if in.CompletedAt != nil {
		out.CompletedAt = in.CompletedAt.DeepCopy()
	}
	if in.ItemCounts != nil {
		out.ItemCounts = new(BackupItemCounts)
		*out.ItemCounts = *in.ItemCounts
	}
}

func (in *USBBackupStatus) DeepCopy() *USBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(USBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackup) DeepCopyInto(out *USBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBBackup) DeepCopy() *USBBackup {
	if in == nil {
		return nil
	}
	out := new(USBBackup)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackup) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBBackupList) DeepCopyInto(out *USBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBBackup, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBBackupList) DeepCopy() *USBBackupList {
	if in == nil {
		return nil
	}
	out := new(USBBackupList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBBackupList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- USBRestore DeepCopy ---

func (in *RestoreBackupRef) DeepCopyInto(out *RestoreBackupRef) { *out = *in }

func (in *RestoreBackupRef) DeepCopy() *RestoreBackupRef {
	if in == nil {
		return nil
	}
	out := new(RestoreBackupRef)
	in.DeepCopyInto(out)
	return out
}

func (in *PreRestoreHealthCheck) DeepCopyInto(out *PreRestoreHealthCheck) {
	*out = *in
	if in.CheckedAt != nil {
		out.CheckedAt = in.CheckedAt.DeepCopy()
	}
}

func (in *PreRestoreHealthCheck) DeepCopy() *PreRestoreHealthCheck {
	if in == nil {
		return nil
	}
	out := new(PreRestoreHealthCheck)
	in.DeepCopyInto(out)
	return out
}

func (in *ConnectionRevalidation) DeepCopyInto(out *ConnectionRevalidation) {
	*out = *in
	if in.TerminatedConnections != nil {
		out.TerminatedConnections = make([]string, len(in.TerminatedConnections))
		copy(out.TerminatedConnections, in.TerminatedConnections)
	}
}

func (in *ConnectionRevalidation) DeepCopy() *ConnectionRevalidation {
	if in == nil {
		return nil
	}
	out := new(ConnectionRevalidation)
	in.DeepCopyInto(out)
	return out
}

func (in *RestoreItemCounts) DeepCopyInto(out *RestoreItemCounts) { *out = *in }

func (in *RestoreItemCounts) DeepCopy() *RestoreItemCounts {
	if in == nil {
		return nil
	}
	out := new(RestoreItemCounts)
	in.DeepCopyInto(out)
	return out
}

func (in *USBRestoreSpec) DeepCopyInto(out *USBRestoreSpec) {
	*out = *in
	out.BackupRef = in.BackupRef
}

func (in *USBRestoreSpec) DeepCopy() *USBRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(USBRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *USBRestoreStatus) DeepCopyInto(out *USBRestoreStatus) {
	*out = *in
	if in.PreRestoreHealthCheck != nil {
		out.PreRestoreHealthCheck = new(PreRestoreHealthCheck)
		in.PreRestoreHealthCheck.DeepCopyInto(out.PreRestoreHealthCheck)
	}
	if in.RestoredItems != nil {
		out.RestoredItems = new(RestoreItemCounts)
		*out.RestoredItems = *in.RestoredItems
	}
	if in.ConnectionRevalidation != nil {
		out.ConnectionRevalidation = new(ConnectionRevalidation)
		in.ConnectionRevalidation.DeepCopyInto(out.ConnectionRevalidation)
	}
	if in.CompletedAt != nil {
		out.CompletedAt = in.CompletedAt.DeepCopy()
	}
}

func (in *USBRestoreStatus) DeepCopy() *USBRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(USBRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *USBRestore) DeepCopyInto(out *USBRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *USBRestore) DeepCopy() *USBRestore {
	if in == nil {
		return nil
	}
	out := new(USBRestore)
	in.DeepCopyInto(out)
	return out
}

func (in *USBRestore) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *USBRestoreList) DeepCopyInto(out *USBRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]USBRestore, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *USBRestoreList) DeepCopy() *USBRestoreList {
	if in == nil {
		return nil
	}
	out := new(USBRestoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *USBRestoreList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
