apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usbdeviceapprovals.usb-fabric.io
spec:
  group: usb-fabric.io
  names:
    kind: USBDeviceApproval
    listKind: USBDeviceApprovalList
    plural: usbdeviceapprovals
    singular: usbdeviceapproval
    shortNames: [usbapproval]
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
            status:
              type: object
      subresources:
        status: {}
